import Head from 'next/head'
import Layout from '@components/Layout';
import Container from '@components/Container';
import Button from '@components/Button';
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

import styles from '@styles/Page.module.scss'
import Link from 'next/link';

export default function Category({ category, products}) {
  return (
    <Layout>
      <Head>
        <title>Tiny Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>{ category.name }</h1>

        <h2>Produits</h2>

        <ul className={styles.products}>
          {products.map(product => {
            return (
              <li key={product.slug}>
                <Link href={`/products/${product.slug}`}>
                  <a>
                    <div className={styles.productImage}>
                      <img width={product.width} height={product.height} src={product.image.url} alt={product.slug} />
                    </div>
                    <h3 className={styles.productTitle}>
                      { product.name }
                    </h3>
                    <p className={styles.productPrice}>
                      { product.price } XAF
                    </p>
                  </a>
                </Link>
                <p>
                  <Button className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-price={product.price}
                    data-item-url={`/products/${product.slug}`}
                    data-item-image={product.image.url}
                    data-item-name={product.name}>
                    Ajouter au panier
                  </Button>
                </p>
              </li>
            )
          })}
        </ul>
      </Container>
    </Layout>
  )
}

export async function getStaticProps({ params }) {
  const client = new ApolloClient({
    uri: 'https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/clyhyneju013107ti6bka6y62/master',
    cache: new InMemoryCache()
  });

  const {data} = await client.query({
    query: gql`
      query getCategory($slug: String) {
        category(where: {slug: $slug}) {
          id
          name
          slug
          product {
            id
            name
            price
            slug
            image
          }
        }
      }
    `,
    variables: {
      slug: params.categorySlug
    }
  });

  const category = data.category
  return {
    props: {
      category,
      products: category.product
    }
  }
}

export async function getStaticPaths() {
  const client = new ApolloClient({
    uri: 'https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/clyhyneju013107ti6bka6y62/master',
    cache: new InMemoryCache()
  });

  const {data} = await client.query({
    query: gql`
      query CategoryPage {
        categories {
          id
          slug
        }
      }
    `
  });
  
  const paths = data.categories.map(category => {
    return {
      params: {
        categorySlug: category.slug
      }
    }
  })
  console.log(paths)
  return {
    paths,
    fallback: false
  }
}