import Head from 'next/head'

import Layout from '@components/Layout';
import Header from '@components/Header';
import Container from '@components/Container';
import Button from '@components/Button';

import styles from '@styles/Page.module.scss'

export default function Category() {
  return (
    <Layout>
      <Head>
        <title>Tiny Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>Nom de la catégorie</h1>

        <h2>Produits</h2>

        <ul className={styles.products}>
          <li>
            <a href="#">
              <div className={styles.productImage}>
                Image
              </div>
              <h3 className={styles.productTitle}>
                Nom du produit
              </h3>
              <p className={styles.productPrice}>
                Prix du produit
              </p>
            </a>
            <p>
              <Button>
                Ajouter au panier
              </Button>
            </p>
          </li>
        </ul>
      </Container>
    </Layout>
  )
}