import Head from 'next/head'
import { FaExternalLinkAlt } from 'react-icons/fa';
import { useState } from 'react';
import Layout from '@components/Layout';
import Container from '@components/Container';
import Map from '@components/Map';

import styles from '@styles/Page.module.scss';
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import center from '@turf/center';
import { points } from '@turf/helpers';

export default function Stores({ storeLocations }) {
  const positions = [];
  const features = points(storeLocations.map(({location}) => {
    return [location.latitude, location.longitude]
  }));
  const [defaultLatitude, defaultLongitude] = center(features)?.geometry.coordinates;
  const [activeStore, setActiveStore] = useState([defaultLatitude, defaultLongitude]);
  const [zoom, setZoom] = useState(7);

  return (
    <Layout>
      <Head>
        <title>Our Stores</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>Locations</h1>

        <div className={styles.stores}>

          <div className={styles.storesLocations}>
            <ul className={styles.locations}>
              { storeLocations.map(store => {
                positions.push({location: store.location, name: store.name, address: store.address, id: store.id});
                
                function handleOnClick() {
                  setActiveStore([store.location.latitude, store.location.longitude]);
                  setZoom(15);
                }

                return (
                  <li key={store.id}>
                    <p className={styles.locationName}>
                      {store.name}
                    </p>
                    <address>
                      {store.address}
                    </address>
                    <p>
                      {store.phoneNumber}
                    </p>
                    <p className={styles.locationDiscovery}>
                      <button onClick={handleOnClick}>
                        View on Map
                      </button>
                      <a href={`https://www.google.com/maps/dir//${store.location.latitude},${store.location.longitude}/@${store.location.latitude},${store.location.longitude},17z/`} target="_blank" rel="noreferrer">
                        Get Directions
                        <FaExternalLinkAlt />
                      </a>
                    </p>
                  </li>
                );
              })}
            </ul>
          </div>

          <div className={styles.storesMap}>
            <div className={styles.storesMapContainer}>
                <Map className={styles.map} center={activeStore} positions={positions} zoom={zoom} />
            </div>
          </div>
        </div>
      </Container>
    </Layout>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/clyhyneju013107ti6bka6y62/master',
    cache: new InMemoryCache()
  });

  const {data} = await client.query({
    query: gql`
      query Locations {
        storeLocations {
          address
          id
          name
          phoneNumber
          location {
            latitude
            longitude
          }
        }
      }
    `
  });
  console.log(data);
  const storeLocations = data.storeLocations;

  return {
    props: {
      storeLocations
    }
  }
}